apiVersion: v2
name: flux2-sync
version: 0.4.1

description: A Helm chart for flux2 GitRepository to sync with
sources:
  - https://github.com/fluxcd-community/helm-charts

type: application
annotations:
  artifacthub.io/changes: |
    - "[Update]: Update chart README related to underlying App Version update to upstream 0.31.0"
