secret:
  # -- Create a secret for the git repository. Defaults to false.
  create: false

  # -- Data of the secret.
  # For HTTPS repositories the secret must contain username and password fields.
  # For SSH repositories the secret must contain identity, identity.pub and known_hosts fields.
  # Values will be encoded to base64 by the helm chart.
  data: {}

  # -- Algorithm of keys to generate.
  # If `data` object above is empty, and `create` is set to true. The Chart will generate the
  # Git SSH key secret automatically based on the key algorithms that are set below.
  generate:
    sshKeyAlgorithm: ecdsa
    sshEcdsaCurve: p521

cli:
  image: ghcr.io/fluxcd/flux-cli
  tag: v2.3.0
  nodeSelector: {}
  affinity: {}
  tolerations: []

gitRepository:
  labels: {}
  annotations: {}
  name: ""
  spec:
    # -- The repository URL, can be an HTTP/S or SSH address.
    url: ""

    # -- _Optional_ The secret name containing the Git credentials.
    # For HTTPS repositories the secret must contain username and password fields.
    # For SSH repositories the secret must contain identity, identity.pub and known_hosts fields.
    # If a secret.create is set, it will point to that one.
    secretRef: {}

    # -- The interval at which to check for repository updates.
    interval: 5m

    # -- _Optional_ The timeout for remote Git operations like cloning, defaults to 20s.
    timeout: ""

    # -- _Optional_ The Git reference to checkout and monitor for changes, defaults to master branch.
    ref:
      branch: master

    # -- _Optional_ Verify OpenPGP signature for the Git commit HEAD points to.
    verify: {}

    # -- _Optional_ Ignore overrides the set of excluded patterns in the .sourceignore format (which is the same as .gitignore). If not provided, a default will be used, consult the documentation for your version to find out what those are. Make sure to set this as yaml multiline string.
    ignore: ""

    # -- _Optional_ This flag tells the controller to suspend the reconciliation of this source.
    suspend: ""

    # -- _Optional_ Determines which git client library to use. Defaults to go-git, valid values are (‘go-git’, ‘libgit2’).
    gitImplementation: ""

    # -- _Optional_ When enabled, after the clone is created, initializes all submodules within, using their default settings. This option is available only when using the ‘go-git’ GitImplementation.
    recurseSubmodules: false

    # -- _Optional_ Extra git repositories to map into the repository
    include: []


kustomization:
  labels: {}
  annotations: {}
  name: ""
  spec:
    # -- _Optional_ DependsOn may contain a dependency.CrossNamespaceDependencyReference slice with references to Kustomization resources that must be ready before this Kustomization can be reconciled.
    dependsOn: []

    # -- _Optional_ Decrypt Kubernetes secrets before applying them on the cluster.
    decryption: {}

    # -- The interval at which to reconcile the Kustomization.
    interval: 5m

    # -- _Optional_ The interval at which to retry a previously failed reconciliation. When not specified, the controller uses the KustomizationSpec.Interval value to retry failures.
    retryInterval: ""

    # -- _Optional_ The KubeConfig for reconciling the Kustomization on a remote cluster. When specified, KubeConfig takes precedence over ServiceAccountName.
    kubeConfig: {}

    # -- _Optional_ Path to the directory containing the kustomization.yaml
    # file, or the set of plain YAMLs a kustomization.yaml should
    # be generated for. Defaults to ‘None’, which translates to
    # the root path of the SourceRef.
    path: ""

    # -- _Optional_ PostBuild describes which actions to perform on the YAML manifest generated by building the kustomize overlay.
    postBuild: {}

    # -- Prune enables garbage collection. Defaults to true.
    prune: true

    # -- _Optional_ A list of resources to be included in the health assessment.
    healthChecks: []

    # -- _Optional_ Strategic merge and JSON patches, defined as inline YAML objects, capable of targeting objects based on kind, label and annotation selectors.
    patches: []

    # -- _Optional_ Images is a list of (image name, new name, new tag or digest) for changing image names, tags or digests. This can also be achieved with a patch, but this operator is simpler to specify.
    images: []

    # -- _Optional_ The name of the Kubernetes service account to impersonate when reconciling this Kustomization.
    serviceAccountName: ""

    # -- _Optional_ This flag tells the controller to suspend subsequent kustomize executions, it does not apply to already started executions. Defaults to false.
    suspend: ""

    # -- _Optional_ TargetNamespace sets or overrides the namespace in the kustomization.yaml file.
    targetNamespace: ""

    # -- _Optional_ Timeout for validation, apply and health checking operations. Defaults to ‘Interval’ duration
    timeout: ""

    # -- _Optional_ Force instructs the controller to recreate resources when patching fails due to an immutable field change. Defaults to false.
    force: false

    # -- _Optional_ Wait instructs the controller to check the health of all the reconciled resources. When enabled, the HealthChecks are ignored. Defaults to false.
    wait: false

# -- _Optional_ If you want multiple subdirectories which depend on each other in the same repo. Their name is derived from their path.
kustomizationlist: {}
# - spec:
#     interval: 5m
#     path: ./base
#     prune: true
#     timeout: 5m
# - spec:
#     dependsOn:
#     - path: ./base
#     interval: 5m
#     path: ./test
#     prune: true
#     timeout: 5m
