annotations:
  artifacthub.io/changes: |
    - "[Chore]: Allow Disabling Pre-Install Job"
apiVersion: v2
appVersion: 2.7.2
description: A Helm chart for flux2
name: flux2
sources:
- https://github.com/fluxcd-community/helm-charts
type: application
version: 2.17.1
