apiVersion: v2
name: flux2
description: A Helm chart for flux2
type: application
version: 0.12.1
appVersion: 0.26.3
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Update]: Update App Version to upstream 0.26.3"
