annotations:
  artifacthub.io/changes: |
    - "feat: add ingress resource for notificationController's receiver webhook service"
apiVersion: v2
appVersion: 2.1.2
description: A Helm chart for flux2
name: flux2
sources:
- https://github.com/fluxcd-community/helm-charts
type: application
version: 2.11.1
