{{- if and .Values.helmcontroller.create}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    control-plane: controller
  name: helm-controller
spec:
  {{- if kindIs "invalid" .Values.helmcontroller.replicas }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.helmcontroller.replicas  }}
  {{- end}}
  selector:
    matchLabels:
      app: helm-controller
  template:
    metadata:
      {{- with .Values.helmcontroller.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: helm-controller
{{ with .Values.helmcontroller.labels }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
    {{- if .Values.helmcontroller.initContainers}}
      initContainers:
        {{- toYaml .Values.helmcontroller.initContainers | nindent 8}}
    {{- end}}
      containers:
      - args:
        {{- if .Values.multitenancy.enabled }}
        - --no-cross-namespace-refs=true
        - --default-service-account={{ .Values.multitenancy.defaultServiceAccount | default "default"  }}
        {{- end}}
        - --events-addr={{ .Values.eventsaddr }}
        - --watch-all-namespaces={{ .Values.watchallnamespaces }}
        - --log-level={{ .Values.loglevel | default "info" }}
        - --log-encoding=json
        - --enable-leader-election
        {{- range .Values.helmcontroller.container.additionalargs }}
        - {{ . }}
        {{- end}}
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ template "template.image" .Values.helmcontroller }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 8080
          name: http-prom
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        {{- with .Values.helmcontroller.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.helmcontroller.securityContext }}
        securityContext: {{ toYaml .Values.helmcontroller.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        {{- end}}
        volumeMounts:
        - mountPath: /tmp
          name: temp
        {{- if .Values.helmcontroller.volumeMounts }}
        {{- toYaml .Values.helmcontroller.volumeMounts | nindent 8 }}
        {{- end}}
      serviceAccountName: helm-controller
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: temp
      {{- if .Values.helmcontroller.volumes }}
      {{- toYaml .Values.helmcontroller.volumes | nindent 6 }}
      {{- end}}
      {{- with .Values.helmcontroller.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.helmcontroller.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.helmcontroller.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
