{{- if and .Values.imageautomationcontroller.create}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    control-plane: controller
  name: image-automation-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-automation-controller
  template:
    metadata:
      {{- with .Values.imageautomationcontroller.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: image-automation-controller
{{ with .Values.imageautomationcontroller.labels }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      {{- if .Values.imageautomationcontroller.initContainers}}
      initContainers:
        {{- toYaml .Values.imageautomationcontroller.initContainers | nindent 8}}
      {{- end}}
      containers:
      - args:
        - --events-addr={{ .Values.eventsaddr }}
        - --watch-all-namespaces={{ .Values.watchallnamespaces }}
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ template "template.image" .Values.imageautomationcontroller }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 8080
          name: http-prom
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        {{- with .Values.imageautomationcontroller.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.imageautomationcontroller.securityContext }}
        securityContext: {{ toYaml .Values.imageautomationcontroller.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        {{- end}}
        volumeMounts:
        - mountPath: /tmp
          name: temp
        {{- if .Values.imageautomationcontroller.volumeMounts }}
        {{- toYaml .Values.imageautomationcontroller.volumeMounts | nindent 8 }}
        {{- end}}
      securityContext:
        fsGroup: 1337
      serviceAccountName: image-automation-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: temp
      {{- if .Values.imageautomationcontroller.volumes }}
      {{- toYaml .Values.imageautomationcontroller.volumes | nindent 6 }}
      {{- end}}
      {{- with .Values.imageautomationcontroller.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imageautomationcontroller.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imageautomationcontroller.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
