{{- if .Values.crds.migration.enabled -}}
{{- if and .Values.rbac.create .Values.multitenancy.enabled (not .Values.multitenancy.privileged) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-flux-migrate
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-10"
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions/status
    verbs:
    - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-flux-migrate
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "-10"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-flux-migrate
subjects:
  - kind: ServiceAccount
    name: kustomize-controller
    namespace: {{ .Release.Namespace }}
---
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-flux-migrate"
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ .Release.Name }}"
      {{- with .Values.crds.migration.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote  }}
        app.kubernetes.io/part-of: flux
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: Never
      serviceAccountName: "kustomize-controller"
      containers:
      - name: flux-cli-migrate
        image: {{ template "template.image" .Values.cli }}
        command: ["/usr/local/bin/flux", "migrate", "--timeout={{ .Values.crds.migration.timeout }}"]
        {{- with .Values.crds.migration.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.crds.migration.securityContext }}
        securityContext: {{ toYaml .Values.crds.migration.securityContext | nindent 10 }}
        {{- else }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          {{- if not .Values.distro.openshift }}
          runAsUser: 65534
          {{- end}}
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        {{- end}}
        {{- if .Values.crds.migration.volumeMounts }}
        volumeMounts:
        {{- toYaml .Values.crds.migration.volumeMounts | nindent 10 }}
        {{- end}}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      {{- with .Values.crds.migration.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.crds.migration.volumes }}
      volumes:
      {{- toYaml .Values.crds.migration.volumes | nindent 8 }}
      {{- end}}
      {{- with .Values.crds.migration.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crds.migration.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
