{{- if and .Values.installCRDs .Values.sourceWatcher.create }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- with .Values.crds.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    controller-gen.kubebuilder.io/version: v0.19.0
  labels:
    app.kubernetes.io/component: source-watcher
    app.kubernetes.io/instance: '{{ .Release.Namespace }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  name: artifactgenerators.source.extensions.fluxcd.io
spec:
  group: source.extensions.fluxcd.io
  names:
    kind: ArtifactGenerator
    listKind: ArtifactGeneratorList
    plural: artifactgenerators
    shortNames:
    - ag
    singular: artifactgenerator
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: ArtifactGenerator is the Schema for the artifactgenerators API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ArtifactGeneratorSpec defines the desired state of ArtifactGenerator.
            properties:
              artifacts:
                description: OutputArtifacts is a list of output artifacts to be generated.
                items:
                  description: |-
                    OutputArtifact defines the desired state of an ExternalArtifact
                    generated by the ArtifactGenerator.
                  properties:
                    copy:
                      description: |-
                        Copy defines a list of copy operations to perform from the sources to the generated artifact.
                        The copy operations are performed in the order they are listed with existing files
                        being overwritten by later copy operations.
                      items:
                        properties:
                          exclude:
                            description: |-
                              Exclude specifies a list of glob patterns to exclude
                              files and dirs matched by the 'From' field.
                            items:
                              type: string
                            maxItems: 100
                            type: array
                          from:
                            description: |-
                              From specifies the source (by alias) and the glob pattern to match files.
                              The format is "@<alias>/<glob-pattern>".
                            maxLength: 1024
                            pattern: ^@([a-z0-9]([a-z0-9_-]*[a-z0-9])?)/(.*)$
                            type: string
                          strategy:
                            description: |-
                              Strategy specifies the copy strategy to use.
                              'Overwrite' will overwrite existing files in the destination.
                              'Merge' is for merging YAML files using Helm values merge strategy.
                              If not specified, defaults to 'Overwrite'.
                            enum:
                            - Overwrite
                            - Merge
                            type: string
                          to:
                            description: |-
                              To specifies the destination path within the artifact.
                              The format is "@artifact/path", the alias "artifact"
                              refers to the root path of the generated artifact.
                            maxLength: 1024
                            pattern: ^@(artifact)/(.*)$
                            type: string
                        required:
                        - from
                        - to
                        type: object
                      minItems: 1
                      type: array
                    name:
                      description: Name is the name of the generated artifact.
                      maxLength: 253
                      pattern: ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$
                      type: string
                    originRevision:
                      description: |-
                        OriginRevision is used to set the 'org.opencontainers.image.revision'
                        annotation on the generated artifact metadata.
                        If specified, it must point to an existing source alias in the format "@<alias>".
                        If the referenced source has an origin revision (e.g. a Git commit SHA),
                        it will be used to set the annotation on the generated artifact.
                        If the referenced source does not have an origin revision, the field is ignored.
                      maxLength: 64
                      pattern: ^@([a-z0-9]([a-z0-9_-]*[a-z0-9])?)$
                      type: string
                    revision:
                      description: |-
                        Revision is the revision of the generated artifact.
                        If specified, it must point to an existing source alias in the format "@<alias>".
                        If not specified, the revision is automatically set to the digest of the artifact content.
                      maxLength: 64
                      pattern: ^@([a-z0-9]([a-z0-9_-]*[a-z0-9])?)$
                      type: string
                  required:
                  - copy
                  - name
                  type: object
                maxItems: 1000
                minItems: 1
                type: array
              sources:
                description: |-
                  Sources is a list of references to the Flux source-controller
                  resources that will be used to generate the artifact.
                items:
                  description: SourceReference contains the reference to a Flux source-controller
                    resource.
                  properties:
                    alias:
                      description: |-
                        Alias of the source within the ArtifactGenerator context.
                        The alias must be unique per ArtifactGenerator, and must consist
                        of lower case alphanumeric characters, underscores, and hyphens.
                        It must start and end with an alphanumeric character.
                      maxLength: 63
                      pattern: ^[a-z0-9]([a-z0-9_-]*[a-z0-9])?$
                      type: string
                    kind:
                      description: Kind of the source.
                      enum:
                      - Bucket
                      - GitRepository
                      - OCIRepository
                      type: string
                    name:
                      description: Name of the source.
                      maxLength: 253
                      pattern: ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$
                      type: string
                    namespace:
                      description: |-
                        Namespace of the source.
                        If not provided, defaults to the same namespace as the ArtifactGenerator.
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                      type: string
                  required:
                  - alias
                  - kind
                  - name
                  type: object
                maxItems: 1000
                minItems: 1
                type: array
            required:
            - artifacts
            - sources
            type: object
          status:
            description: ArtifactGeneratorStatus defines the observed state of ArtifactGenerator.
            properties:
              conditions:
                description: Conditions holds the conditions for the ArtifactGenerator.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              inventory:
                description: Inventory contains the list of generated ExternalArtifact
                  references.
                items:
                  description: |-
                    ExternalArtifactReference contains the reference to a
                    generated ExternalArtifact along with its digest.
                  properties:
                    digest:
                      description: Digest of the referent artifact.
                      type: string
                    filename:
                      description: Filename is the name of the artifact file.
                      type: string
                    name:
                      description: Name of the referent artifact.
                      type: string
                    namespace:
                      description: Namespace of the referent artifact.
                      type: string
                  required:
                  - digest
                  - filename
                  - name
                  - namespace
                  type: object
                type: array
              lastHandledReconcileAt:
                description: |-
                  LastHandledReconcileAt holds the value of the most recent
                  reconcile request value, so a change of the annotation value
                  can be detected.
                type: string
              observedSourcesDigest:
                description: |-
                  ObservedSourcesDigest is a hash representing the current state of
                  all the sources referenced by the ArtifactGenerator.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
