apiVersion: v2
name: flux2-notification
type: application
version: 0.5.0
appVersion: 0.29.1
description: A Helm chart for flux2 alerts and the needed providers and secrets
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Update]: Update App Version to upstream 0.29.1"
