apiVersion: v2
name: flux2-notification
type: application
version: 1.12.1
appVersion: 2.1.1
description: A Helm chart for flux2 alerts and the needed providers and secrets
sources:
  - https://github.com/fluxcd-community/helm-charts
annotations:
  artifacthub.io/changes: |
    - "[Chore]: Update App Version to upstream 2.1.1"
