name: e2e-sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind
          node_image: kindest/node:v1.25.11
      - name: Setup Helm
        uses: fluxcd/pkg//actions/helm@main
        with:
          version: 3.10.1
      - name: Install
        run: |
          helm upgrade --install --debug flux2 ./charts/flux2 \
          --namespace=flux-system \
          --create-namespace \
          --wait \
          --wait-for-jobs
      - name: Check install
        run: |
          flux check --namespace flux-system
      - name: Sync
        run: |
          helm upgrade --install --debug podinfo ./charts/flux2-sync \
          --namespace=podinfo \
          --create-namespace \
          --set gitRepository.spec.url=https://github.com/stefanprodan/podinfo.git \
          --set gitRepository.spec.ref.branch=master \
          --set kustomization.spec.path=kustomize \
          --set kustomization.spec.targetNamespace=podinfo \
          --set kustomization.spec.wait=true \
          --set kustomization.spec.timeout=2m
      - name: Check sync
        run: |
          flux reconcile kustomization podinfo --with-source --namespace podinfo
      - name: Delete Sync
        run: |
          helm delete --debug podinfo \
          --namespace=podinfo
      - name: Uninstall
        run: |
          helm uninstall --debug flux2 \
          --namespace=flux-system
      - name: Install with Multi-tenancy
        run: |
          helm upgrade --install --debug flux2 ./charts/flux2 \
          --namespace=flux-system \
          --create-namespace \
          --wait \
          --wait-for-jobs \
          --set multitenancy.enabled=true
      - name: Uninstall the Multi-Tenancy setup
        run: |
          helm uninstall --debug flux2 \
          --namespace=flux-system
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
